name: dart_exam_lamtran
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  shelf: ^1.0.0
  shelf_static: ^1.0.0
  shelf_router: ^1.0.0
  mustache_template: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
